'use client';

import { useState } from 'react';
import { NatoSymbol } from './NatoSymbol';
import { 
  AFFILIATIONS, 
  UNIT_TYPES, 
  ECHELONS,
  UNIT_CATEGORIES,
  AFFILIATION_LABELS,
  ECHELON_LABELS,
  AffiliationKey,
  UnitTypeKey,
  EchelonKey
} from '@/lib/milsymbol/constants';

export function UnitCreator() {
  const [affiliation, setAffiliation] = useState<AffiliationKey>('friendly');
  const [type, setType] = useState<UnitTypeKey>('infantaria');
  const [echelon, setEchelon] = useState<EchelonKey>('company');

  // Compute the 15-character SIDC string
  // Format: S + [Affiliation] + [Dimension] + P + [Code (6)] + [Modifier 11 (-)] + [Echelon] + ---
  const affiliationCode = AFFILIATIONS[affiliation];
  const typeDef = UNIT_TYPES[type];
  const echelonCode = ECHELONS[echelon];
  
  const sidc = `S${affiliationCode}${typeDef.dimension}P${typeDef.code}-${echelonCode}---`;

  return (
    <div className="flex flex-col md:flex-row gap-8 p-6 border rounded-lg bg-white shadow-sm w-full max-w-2xl text-black">
      
      {/* Live Preview generated by milsymbol */}
      <div className="w-48 h-48 flex flex-col items-center justify-center bg-slate-50 border rounded-lg p-4">
        <NatoSymbol sidc={sidc} size={80} />
        <span className="mt-4 text-xs font-mono text-gray-400 select-all">{sidc}</span>
      </div>

      {/* Controls */}
      <div className="flex flex-col gap-5 flex-grow">
        <h3 className="text-lg font-semibold border-b pb-2">Criador de Unidade</h3>
        
        <label className="flex flex-col text-sm font-medium text-gray-700">
          Afiliação / Força
          <select 
            className="mt-1 p-2 border rounded-md bg-white focus:ring-2 focus:ring-blue-500"
            value={affiliation} 
            onChange={(e) => setAffiliation(e.target.value as AffiliationKey)}
          >
            {Object.keys(AFFILIATIONS).map((key) => (
              <option key={key} value={key}>
                {AFFILIATION_LABELS[key as AffiliationKey] || key}
              </option>
            ))}
          </select>
        </label>

        <label className="flex flex-col text-sm font-medium text-gray-700">
          Tipo de Unidade
          <select 
            className="mt-1 p-2 border rounded-md bg-white focus:ring-2 focus:ring-blue-500"
            value={type} 
            onChange={(e) => setType(e.target.value as UnitTypeKey)}
          >
            {UNIT_CATEGORIES.map((category) => (
              <optgroup key={category} label={category}>
                {Object.entries(UNIT_TYPES)
                  .filter(([, def]) => def.category === category)
                  .map(([key, def]) => (
                    <option key={key} value={key}>{def.label}</option>
                  ))}
              </optgroup>
            ))}
          </select>
        </label>

        <label className="flex flex-col text-sm font-medium text-gray-700">
          Escalão
          <select 
            className="mt-1 p-2 border rounded-md bg-white focus:ring-2 focus:ring-blue-500"
            value={echelon} 
            onChange={(e) => setEchelon(e.target.value as EchelonKey)}
          >
            {Object.keys(ECHELONS).map((key) => (
              <option key={key} value={key}>
                {ECHELON_LABELS[key as EchelonKey] || key}
              </option>
            ))}
          </select>
        </label>
      </div>
    </div>
  );
}
